using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;


namespace Iunotaisho.models
{

    public class BlogSchema 
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; };

        // external ID or key, which may be easier to reference (ex: 1,2,3 etc.)
        public string Id { get; set; }

        public string Author { get; set; }
        public string Preview { get; set; }
        public string Subject { get; set; }
        public string Post { get; set; }
        public DateTime UpdatedOn { get; set; } = DateTime.Now;
        public DateTime CreatedOn { get; set; } = DateTime.Now;
    }

}

