using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace IunotaishoVue.models
{

    public class ContactSchema
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; };

        // external ID or key, which may be easier to reference (ex: 1,2,3 etc.)
        public string Id { get; set; }

        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
    }

}
