using System;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace Iunotaisho.models
{

    public class UserSchema
    {
        [BsonId]
        // standard BSonId generated by MongoDb
        public ObjectId InternalId { get; set; }

        // external ID or key, which may be easier to reference (ex: 1,2,3 etc.)
        public string Id { get; set; }

        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
    }

}